### PR TITLE
ci(*): typescript-eslint 8

### PR DESCRIPTION
**Pull request by vr-varad**
# Overview

## PR Checklist

- [ ] I did below actions if need

1. I read the [Contributing Guide](https://github.com/toss/suspensive/blob/main/CONTRIBUTING.md)
2. I added documents and tests.

### CODE REVIEW

**Comment by vr-varad** [comment]
@manudeli

**Comment by manudeli** [comment]
@vr-varad Could you resolve ci:eslint please?

**Comment by vr-varad** [comment]
`0:0  error  Parsing error: "parserOptions.project" has been provided for @typescript-eslint/parser.
The file was not found in any of the provided project(s): eslint.config.mjs`
I am getting this error in suspensive/examples/vite-react-18-suspense-prerender-siblings-problem/eslint.config.mjs, do u have any idea what's it about? @manudeli

**Comment by manudeli** [comment]
> `0:0 error Parsing error: "parserOptions.project" has been provided for @typescript-eslint/parser. The file was not found in any of the provided project(s): eslint.config.mjs` I am getting this error in suspensive/examples/vite-react-18-suspense-prerender-siblings-problem/eslint.config.mjs, do u have any idea what's it about? @manudeli

So I need your help..! Actually I got same error before. Could you resolve that error please?

**Comment by saul-atomrigs** [comment]
The `no-throw-literal` rule has been renamed to `only-throw-error` (https://github.com/typescript-eslint/typescript-eslint/pull/8701).
So for https://github.com/toss/suspensive/pull/1240#issuecomment-2322917332, I think instead of https://github.com/toss/suspensive/pull/1240/commits/488d9f7e4d422b7747f6c02a557167e1fe055bb3, it's better to use `only-throw-error`:

```
'@typescript-eslint/only-throw-error': 'warn',
```

**Comment by saul-atomrigs** [comment]
> 0:0  error  Parsing error: "parserOptions.project" has been provided for @typescript-eslint/parser. The file was not found in any of the provided project(s): eslint.config.mjs
I am getting this error in suspensive/examples/vite-react-18-suspense-prerender-siblings-problem/eslint.config.mjs, do u have any idea what's it about? @manudeli

This error log is mentioned in recent typescript-eslint issues (https://github.com/typescript-eslint/typescript-eslint/issues/9774, https://github.com/typescript-eslint/typescript-eslint/issues/9749). It seems like the solution is adding `allowJs` to the `tsconfig.json`s, but in my case doing this leads to hidden lint errors being thrown, which are quite a lot.....

**Comment by manudeli** [comment]
I close this Pull Request because of #1326. @SEOKKAMONI but co-author please these people(@vr-varad, @saul-atomrigs) too. We struggled to solve this issue in this pull request

**Pull request closed without merging**
