### PR TITLE
docs: update discord link in nav

### LINKED ISSUE #1259: [Feature]: update Discord link
### Package Scope

etc

### Description

toss opensource discord link

### Possible Solution

_No response_

### etc.

_No response_

### PR DESCRIPTION
**Pull request by gwansikk**
close #1259 

# Overview

## PR Checklist

- [x] I did below actions if need

1. I read the [Contributing Guide](https://github.com/toss/suspensive/blob/main/CONTRIBUTING.md)
2. I added documents and tests.

### CODE REVIEW

**Comment by manudeli** [comment]
@gwansikk I updated link for going suspensive channel directly

**Comment by manudeli** [comment]
I add @BasixKOR as co-author too. Thanks for issuing this!

**Comment by gwansikk** [comment]
> @gwansikk I updated link for going suspensive channel directly

Do we also need to update the links in the README.md file?

**Comment by manudeli** [comment]
> > @gwansikk I updated link for going suspensive channel directly
> 
> Do we also need to update the links in the `README.md`?

Yes, It will be better for gathering people interested in suspensive more easily

**Review by manudeli — APPROVED** [review]
Thanks! 👍

**Pull request merged**
