### PR TITLE
test(react-query): add test code for copy function

### PR DESCRIPTION
**Pull request by fe-dudu**
# Overview

- add test code for copy function

### before
before

### after
after

## PR Checklist

- [x] I did below actions if need

1. I read the [Contributing Guide](https://github.com/toss/suspensive/blob/main/CONTRIBUTING.md)
2. I added documents and tests.

### CODE REVIEW

**Comment by gwansikk** [comment]
@fe-dudu  Thank you for your contribution. the testing of this function has become more robust.

**Comment by manudeli** [comment]
https://github.com/toss/suspensive/actions/runs/10123937476/job/27997896523?pr=1151

@kangju2000 Check that error please. In my opinion, we can remove that action for now

**Review by gwansikk — APPROVED** [review]

**Review by manudeli — APPROVED** [review]
Thanks👍

**Comment by kangju2000** [comment]
> https://github.com/toss/suspensive/actions/runs/10123937476/job/27997896523?pr=1151
> 
> @kangju2000 Check that error please. In my opinion, we can remove that action for now

@manudeli 
This PR resolves the issue! https://github.com/toss/suspensive/pull/1152

**Pull request merged**
