### PR TITLE
fix(react-native): fix jest error in react native

### PR DESCRIPTION
**Pull request by gwansikk**
# Overview

- https://github.com/callstack/react-native-testing-library/issues/1559

## PR Checklist

- [x] I did below actions if need

1. I read the [Contributing Guide](https://github.com/toss/suspensive/blob/main/CONTRIBUTING.md)
2. I added documents and tests.

### CODE REVIEW

**Comment by gwansikk** [comment]
image

I resolved the issues in the CI on my local environment, but they are still occurring in GitHub Actions. I am looking for other solutions. 😂

**Comment by manudeli** [comment]
Sorry It's my bad, could you version down for react-native? Maybe It will resolve this ci error

**Comment by manudeli** [comment]
> Sorry It's my bad, could you version down for react-native? Maybe It will resolve this ci error

I'll try it now

**Comment by manudeli** [comment]
@gwansikk Sorrrrrry!! https://github.com/toss/suspensive/commit/b64288031e0f3289824e189e9daafbf5e6732a84 I resolve this error

**Pull request closed without merging**
